version: "3.8"
services:
  postgres:
    image: postgres:16
    container_name: socialapp_db
    environment:
      POSTGRES_DB: socialdb
      POSTGRES_USER: socialuser
      POSTGRES_PASSWORD: socialpass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: